spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: crud-example
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: blog_user
    password: BlogPass123
server:
  port: 2120
