spring:
  application:
    name: crud-example

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: blog_user
    password: BlogPass123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none # ✅ Prevents conflicts if schema is already defined via SQL
    database-platform: org.hibernate.dialect.OracleDialect # ✅ Use this for Hibernate 6+
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always # ✅ Ensures schema.sql + data.sql run
      platform: oracle

server:
  port: 1234